version: '3.5'
services:
  redis:
    image: bitnami/redis:latest
    #    image: redis:4.0.5-alpine
    #    command: ["redis-server", "--appendonly", "yes"]
    #    hostname: redis
    #    networks:
    #      - redis-net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    ports:
      - '6379:6379'
    volumes:
      - redis-vol:/bitnami/redis/data
    networks:
      - database
  #    volumes:
  #      - redis-data:/data
  mysql:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3399:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=podcast
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_PASSWORD=abcd1234
    volumes:
      #      - ./mysql-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_vol:/var/lib/mysql
    networks:
      - database
  db:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=mpcast
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_PASSWORD=abcd1234
    volumes:
      #      - ./mysql-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_vol:/var/lib/mysql
    networks:
      - database
#  caixie.love_api:
#    tty: true
#    stdin_open: true
#    image: mhart/alpine-node
#    build: .
#    expose:
#      - 5000
#    networks:
#      - traefik
#      - db
#    labels:
#      - "traefik.backend=caixie.love_api"
#      - "traefik.docker.network=traefik"
#      - "traefik.enable=true"
#      - "traefik.passHostHeader=true"
#      - "traefik.frontend.priority=11"
#      - "traefik.port=5000"
#      - "traefik.frontend.entryPoints=https,http"
#      - "traefik.frontend.rule=Host:api.caixie.top"
#      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#    volumes:
#      - ./:/app
#    command: ["node", "/app/production.js"]
#    command: ["node", "/app/development.js"]
#    depends_on:
#      - mysql
#      - redis
volumes:
  mysql_vol:
  db_vol:
  redis-vol:
  app-vol:
networks:
  database:
  traefik:
    external:
      name: traefik
